pythonTutorial/udemy/mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='first-posts'))
]

pythonTutorial/udemy/mysite/posts/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url('^$', views.post_list, name='post_list'),
    url('^create/$', views.post_create, name='post_create'),
    url('^(?P<pk>\d+)/edit/$', views.post_update, name='post_update'),
    url('^delete/$', views.post_delete, name='post_delete'),
    url('^(?P<pk>\d+)/$', views.post_detail, name='detail')
 ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pythonTutorial/udemy/mysite/posts/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def get_content_upper(self):
        return self.content.upper()
    get_content_upper.short_description = 'Detail'

    def get_absolute_url(self):
        return reverse('first-posts:detail', kwargs={"pk": self.id})

    def __unicode__(self):
        return self.title

pythonTutorial/udemy/mysite/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        # tell django which model you are using
        model = Post
        # tell django which fields out of the Post model you are using
        fields = [
            'title',
            'content'
        ]

pythonTutorial/udemy/mysite/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Post
from .forms import PostForm


# Create your views here.
def post_create(request):
    if request.method == "GET":
        # Creating a new empty PostForm
        # form = PostForm()

        # create a new PostForm passing an empty dictionary. When we do this. Django performs field validation based on
        # field definition. and then updates the form html to also include errors from fields and errors on the form
        # as a whole. This are built in validation errors. So this is better, because the first time it is requested,
        # we also display what is required
        # may be just use this information to display a red asterik instead of the error msg.
        form = PostForm(request.POST)

        # if for some reason you don't want to use PostForm(request.POST) for GET also, you can use
        # form = PostForm(request.POST or None)  # ie for GET it will be None, and for POST it will be  request.POST
        # so you don't need if else
        context = {
            "form": form
        }
        return render(request, 'post_form.html', context)
    else:
        # request.POST is a dictionary of filled up form data, so we ask Django to populate the form
        # object with all the data sent by the user.
        form = PostForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)  # dont yet commit to DB
            instance.save()  # commit now, so that your model specific save() overrides if any get called. Prefer this
        # separately, you can edit an existing model instance using the form. Like this
        # Eg:
        # a = Post.object.get(pk=2)
        # form = PostForm(None, instance=a)
        # form.save()
        return HttpResponseRedirect(reverse('first-posts:post_list'))


def post_detail(request, pk):
    instance = get_object_or_404(Post, id=pk)
    context = {
        'title': instance.title,
        'instance': instance
    }
    return render(request, 'post_detail.html', context)


def post_list(request):
    queryset = Post.objects.all()
    if request.user.is_authenticated():
        context = {
            "objects_list": queryset,
            "title": "My User List"
        }
    else:
        context = {
            "title": "List"
        }
    return render(request, 'post_list.html', context)


def post_update(request, pk):
    if request.method == "GET":
        instance = get_object_or_404(Post, id=pk)
        form = PostForm(None, instance=instance)
        print form.data.get("title")
        context = {
            'instance': instance,
            'form': form
        }
        return render(request, 'post_update.html', context)
    else:
        instance = get_object_or_404(Post, id=pk)
        form = PostForm(request.POST, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('first-posts:post_list'))


def post_delete(request):
    return HttpResponse("<h1>Delete</h1>")

pythonTutorial/udemy/mysite/posts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {%  block head_title %}
            Try Django 1.9
        {% endblock head_title %}
     </title>


    <!-- Latest compiled and CSS -->
    <script src="{% static 'posts/jquery/jquery-3.1.1.min.js' %}" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'posts/bootstrap-3.3.7/css/bootstrap.css' %}" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static 'posts/bootstrap-3.3.7/css/bootstrap-theme.css' %}" crossorigin="anonymous">
    <!-- Latest compiled and JavaScript -->
    <script src="{% static 'posts/bootstrap-3.3.7/js/bootstrap.js' %}" crossorigin="anonymous"></script>
  <style>
        {% block style %}
        {%  endblock style %}
    </style>
</head>
<body>
<div class="container">
{% block content %}


{% endblock content %}
</div>
</body>
</html>

pythonTutorial/udemy/mysite/posts/templates/post_detail.html
{%  extends 'base.html' %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block style %}
    h1 {
        color: green;
    }
{% endblock style %}

{%  block content %}
    <h1>{{ title }}</h1>
    <div>
        <label>Title: </label> {{ instance.title }}<br/>
        <label>Content: </label> {{ instance.content }}<br/>
        <label>Created: </label> {{ instance.created }}<br/>
        <label>Last Updated: </label> {{ instance.last_updated }}<br/>
        <label>Id: </label> {{ instance.id }}<br/>
    </div>
    <br/>
{% endblock content %}

pythonTutorial/udemy/mysite/posts/templates/post_form.html
{% extends 'base.html' %}


{% block content %}
    <h1>Form</h1>
<form action="{% url 'first-posts:post_create' %}" method="POST">
    {%  csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{%  endblock content %}

pythonTutorial/udemy/mysite/posts/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }} is working!!</h1>
    <p>Base Page</p>
    {% for obj in objects_list %}
        {%  url 'first-posts:detail' pk=obj.id %}
        <a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></br/>
        {{ obj.content }}<br/>
        {{ obj.created }}<br/>
        {{ obj.last_updated }}<br/>
        {{ obj.id }}<br/><br/>
    {%  endfor %}

{% endblock content %}

pythonTutorial/udemy/mysite/posts/templates/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post Form</title>
</head>
<body>
<form action="{% url 'first-posts:post_update' pk=instance.id  %}" method="POST">
    {%  csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Confirm Edit">
</form>
</body>
</html>