pythonTutorial/django/mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace='polls'))
]

pythonTutorial/django/mysite/polls/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
]

pythonTutorial/django/mysite/polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=50)
    # The string argument will be visible in the Admin site. If no argument passed, admin site will show "Pub date"
    # So for question_text field, it will show "Question text"
    pub_date = models.DateTimeField('published on')

    def __unicode__(self):
        return "%s" % self.question_text

    def __str__(self):
        return self.__unicode__()

    def was_published_recently(self):
        yesterday = timezone.now() - timedelta(days=1)
        return yesterday <= self.pub_date <= timezone.now()
    # Marking as boolean will show a red cross mark or a green right mark in the admin page
    was_published_recently.boolean = True
    # Column name to use in the admin page
    was_published_recently.short_description = 'Published recently?'
    # Django does all sorting at the database level. So in the admin page, you will not be able to sort based on this
    # field, as this field is not in the database. You can however enable sorting on this column by piggybacking on some
    # database field, in this case on pub_date by using the admin_order_field
    was_published_recently.admin_order_field = 'pub_date'

    def get_absolute_url(self):
        return reverse('polls:detail', kwargs={'pk': self.id})


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return "%s" % self.choice_text

    def __str__(self):
        return self.__unicode__()

pythonTutorial/django/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.utils import timezone

from .models import Question, Choice


# Use generic views. Generic views are class based views defined by Django.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'questions'  # the context variable name which will be provided in the template.

    def get_queryset(self):
        """ return the last five published questions"""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
        #return Question.objects.order_by('-pub_date')[:5]


# generic.DetailView view will get the Question instance automatically
# DetailView expects a primary key which must be given by the "pk" argument in the URL.
class DetailView(generic.DetailView):
    template_name = 'polls/detail.html'
    model = Question

    def get_queryset(self):
        # This filter will be applied to the record fetched using the pk. If filter fails, then a 404 is thrown
        # automatically.
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    template_name = 'polls/result.html'
    model = Question


@require_http_methods(['POST'])
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question
    }
    try:
        user_choice = Choice.objects.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context['error_message'] = 'You did not vote!!'
        return render(request, 'polls/detail.html', context)
    else:
        user_choice.votes += 1
        user_choice.save()
    return HttpResponseRedirect(reverse('polls:results', kwargs={'pk': question.id}))

pythonTutorial/django/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=display-width, initial-scale=1">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    {%  if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    {% if question.choice_set.all|length > 0 %}
    <form action="{% url 'polls:vote' question.id %}" method="POST">
        {%  csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" id="choice{{ forloop.counter}}" name="choice" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br/>
        {% endfor %}
        <input type="submit" value="Vote" />
    </form>
    {% else %}
        <h3>No choices available.</h3>
    {% endif %}
</body>
</html>

pythonTutorial/django/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=display-width, initial-scale=1">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
    {% if questions %}
        <h1>Recent Questions</h1>
        <br/>
        <ul>
        {% for question in questions %}
        <li><a href="{{ question.get_absolute_url }}">{{ question.question_text }}</a> </li>
        {% endfor %}
        </ul>
    {% else %}
        <h1>No polls available.</h1>
    {% endif %}
</body>
</html>

pythonTutorial/django/mysite/polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=display-width, initial-scale=1">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <h1> {{ question.question_text }}</h1><br/>

    {% for choice in question.choice_set.all %}
    <div>
        {{ choice.choice_text }}  -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
    </div>
    {% endfor %}
</body>
</html>